name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Release build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build --release
        uses: clechasseur/rs-cargo@v4
        with:
          command: build
          args: --release
      - name: Store target tripple
        id: target
        run: echo "target=$(rustc -vV | awk '/^host/ { print $2 }')" >> $GITHUB_OUTPUT
      - run: mkdir artifacts/
      - run: mv target/release/website-tooling artifacts/website-tooling-${{ steps.target.outputs.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-tooling-${{ steps.target.outputs.target }}
          path: artifacts/*

  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: mkdir artifacts/
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: website-tooling-*
          path: artifacts
          merge-multiple: true
      - run: ls -R artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
